# Imports

In [1]:
from PIL import Image
import numpy as np
import pandas as pd
from queue import Queue

# Classes

In [2]:
class Coordinate():
    def __init__(self, i, j):
        self.i = i
        self.j = j

    def isEqual(self, that):
        return self.i == that.i and self.j == that.j

    def distanceTo(self, that):
        return math.sqrt(((self.i - that.i) ** 2) + ((self.j - that.j) ** 2))

    def toString(self):
        return str("[" + str(self.i) + ", " + str(self.j) + "]")

    def range(self, fromNode, toNode):
        return (fromNode.i <= self.i and self.i <= toNode.i and fromNode.j <= self.j and self.j <= toNode.j)

    def setIdentifier(self, identifier):
        self.identifier = identifier
    
    def surrounding(self):
        return [
            Coordinate(self.i, self.j + 1), # to EAST
            Coordinate(self.i + 1, self.j), # to SOUTH
            Coordinate(self.i, self.j - 1), # to WEST
            Coordinate(self.i - 1, self.j) # to NORTH
        ]
    
    def getDirection(self, that):
        i = self.i - that.i
        j = self.j - that.j
        if i != 0:
            return 'N' if i > 0 else 'S'
        elif j != 0:
            return 'W' if j > 0 else 'E'
        else:
            return None
        
            

# Utils

In [3]:
def isDigit(n):
    try:
        int(n)
        return True
    except ValueError:
        return  False

# Functions

In [4]:
def imageToMatrix(image_path, width=None, height=None, threshold=128):

    image = Image.open(image_path)
    image_grey = image.convert('L')

    image_binary = image_grey.point(lambda point : point > threshold and 1)

    if (width is not None and height is not None):
        image_binary = image_binary.resize((width, height), Image.NEAREST)

    nparray = np.array(image_binary).astype(int)
    nparray[nparray == 0] = -1
    nparray[nparray == 1] = -2
    return nparray

In [5]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', 5)

def printMatrix_color(value):
    if isinstance(value, str) and not isDigit(value):
        if value == 'E':
            color = 'yellow'
        elif value == 'W':
            color = 'green'
        elif value == 'N':
            color = 'cyan'
        elif value == 'S':
            color = 'blue'
        else:
            color = 'white'
    else:
        value = int(value)
        if value == -1:
            color = 'black'
        elif value == -2:
            color = 'white'
        elif value == 0:
            color = 'green'
        else:
            color = 'white'
    return 'background-color: %s' % color

def printMatrix(matrix):
    df = pd.DataFrame(matrix)
    return df.style.applymap(printMatrix_color)

In [6]:
def createBFSMatrix(matrix, c):
    BFSMatrix = np.full(matrix.shape, -1)
    BFSMatrix[c.i, c.j] = 0
    fifo = Queue()
    fifo.put(c)
    while not fifo.empty():
        c = fifo.get()
        value = BFSMatrix[c.i, c.j]
        for s in c.surrounding():
            # if in matrix range and the cell is not a block
            if s.range(Coordinate(0, 0), Coordinate(matrix.shape[0] - 1, matrix.shape[1] - 1)):
                if BFSMatrix[s.i, s.j] == -1 and matrix[s.i, s.j] == -2:
                    BFSMatrix[s.i, s.j] = value + 1
                    fifo.put(s)
    return BFSMatrix

In [7]:
def createDirectionMatrix(BFSMatrix):
    directionMatrix = np.full(matrix.shape, '-1')
    for row, col in np.ndindex(directionMatrix.shape):
        c = Coordinate(row, col)
        if BFSMatrix[c.i, c.j] > 0: 
            minimum = float('inf')
            resultCoord = c
            for s in c.surrounding():
                # if in matrix range and the cell is not a block
                if s.range(Coordinate(0, 0), Coordinate(directionMatrix.shape[0] - 1, directionMatrix.shape[1] - 1)):
                    if BFSMatrix[s.i, s.j] >= 0 and BFSMatrix[s.i, s.j] < minimum:
                        resultCoord = s
                        minimum = BFSMatrix[s.i, s.j]
            letter = c.getDirection(resultCoord)
            if letter is not None:
                directionMatrix[c.i, c.j] = letter
    return directionMatrix

In [8]:
def createBFSDepthMatrix(matrix, c):
    BFSDepthMatrix = np.full((5, matrix.shape[0], matrix.shape[1]), -1)
    for it in range(0, 5):
        BFSDepthMatrix[it, c.i, c.j] = 0
    fifo = Queue()
    for index, s in enumerate(c.surrounding()):
        # if in matrix range and the cell is not a block
        if s.range(Coordinate(0, 0), Coordinate(matrix.shape[0] - 1, matrix.shape[1] - 1)) and matrix[s.i, s.j] == -2:
            s.setIdentifier(index + 1)
            fifo.put(s)
            BFSDepthMatrix[s.identifier, s.i, s.j] = 1
    while not fifo.empty():
        c = fifo.get()
        value = BFSDepthMatrix[c.identifier, c.i, c.j]
        for index, s in enumerate(c.surrounding()):
            # if in matrix range and the cell is not a block
            if s.range(Coordinate(0, 0), Coordinate(matrix.shape[0] - 1, matrix.shape[1] - 1)) and matrix[s.i, s.j] == -2:
                s.setIdentifier(index + 1)
                # if has no value set and not the same direction coming from
                if BFSDepthMatrix[s.identifier, s.i, s.j] == -1 and s.identifier % 4 != ((c.identifier + 2) % 4):
                    fifo.put(s)
                    BFSDepthMatrix[s.identifier, s.i, s.j] = value + 1
    for row, col in np.ndindex(BFSDepthMatrix[0].shape):
        values = BFSDepthMatrix[1:, row, col]
        values = values[values != -1]
        if values.size > 0:
            BFSDepthMatrix[0, row, col] = min(values)
    return BFSDepthMatrix

In [9]:
def editCell(BFSDepthMatrix, c):
    modifiedMatrix = np.full((6, BFSDepthMatrix[0].shape[0], BFSDepthMatrix[0].shape[1]), 0)
    modifiedMatrix[:-1, :, :] = BFSDepthMatrix
    fifo = Queue()
    if BFSDepthMatrix[0, c.i, c.j] > 0:
        for index in range(0, 5):
            # if in matrix range and the cell is not a block
            if c.range(Coordinate(0, 0), Coordinate(modifiedMatrix[0].shape[0] - 1, modifiedMatrix[0].shape[1] - 1)):
                modifiedMatrix[index, c.i, c.j] = -1
        for index, s in enumerate(c.surrounding()):
            # if in matrix range and the cell is not a block
            if s.range(Coordinate(0, 0), Coordinate(modifiedMatrix[0].shape[0] - 1, modifiedMatrix[0].shape[1] - 1)) and modifiedMatrix[0, s.i, s.j] != -1:
                s.setIdentifier(index + 1)
                value = modifiedMatrix[s.identifier, s.i, s.j]
                modifiedMatrix[s.identifier, s.i, s.j] = -1
                # need update
                if modifiedMatrix[0, s.i, s.j] == value:
                    values = modifiedMatrix[1:5, s.i, s.j]
                    filteredValues = values[values != -1]
                    if filteredValues.size > 0:
                        modifiedMatrix[0, s.i, s.j] = min(filteredValues)
                    else:
                        modifiedMatrix[0, s.i, s.j] = -1
                    print(modifiedMatrix[0:5, s.i, s.j])
                    s.setIdentifier(values.tolist().index(modifiedMatrix[0, s.i, s.j]))
                    print(s.identifier, s.i, s.j)
                    fifo.put(s)
    else:
        for index, s in enumerate(c.surrounding()):
            # if in matrix range and the cell is not a block
            if s.range(Coordinate(0, 0), Coordinate(modifiedMatrix[0].shape[0] - 1, modifiedMatrix[0].shape[1] - 1)) and modifiedMatrix[0, s.i, s.j] != -1:
                # Reverse direction
                fromIndex = ((index + 1 + 2) % 4) + 1
                # reachable
                modifiedMatrix[fromIndex, c.i, c.j] = modifiedMatrix[0, s.i, s.j] + 1
                initCoord = Coordinate(c.i, c.j)
                initCoord.setIdentifier(fromIndex)
                fifo.put(initCoord)
    while not fifo.empty():
        c = fifo.get()
        value = modifiedMatrix[c.identifier, c.i, c.j]
        #print(c.identifier, c.i, c.j, value)
        for index, s in enumerate(c.surrounding()):
            # if in matrix range and the cell is not a block
            if s.range(Coordinate(0, 0), Coordinate(modifiedMatrix[0].shape[0] - 1, modifiedMatrix[0].shape[1] - 1)) and matrix[s.i, s.j] == -2:
                s.setIdentifier(index + 1)
                # if has no value set and not the same direction coming from
                if s.identifier % 4 != ((c.identifier + 2) % 4):
                    if (value + 1 < modifiedMatrix[s.identifier, s.i, s.j] or modifiedMatrix[s.identifier, s.i, s.j] == -1):
                        fifo.put(s)
                        modifiedMatrix[s.identifier, s.i, s.j] = value + 1
                        modifiedMatrix[5, s.i, s.j] = modifiedMatrix[5, s.i, s.j] + 1
    for row, col in np.ndindex(modifiedMatrix[0].shape):
        values = modifiedMatrix[1:5, row, col]
        values = values[values != -1]
        if values.size > 0:
            modifiedMatrix[0, row, col] = min(values)
        else:
            modifiedMatrix[0, row, col] = -1
    return modifiedMatrix

# Environment Variables

In [10]:
FILENAME = 'D:/compressed-path-database/resources/labyrinth_5.png'
MATRIX_WIDTH = 30
MATRIX_HEIGHT = 20

# Explanation for the remove block process

First of all create the matrix, it is compound by two values, -2 is accesible and -1 is a block, not accesible

In [11]:
matrix = imageToMatrix(FILENAME, MATRIX_WIDTH, MATRIX_HEIGHT)
printMatrix(matrix)

Creation of the matrix to be used, it is compound of 5 layers of input image. That is, a matrix of dimension of (5 x N x M) where N and M is the dimension of the input image

In [12]:
BFSDepthMatrix = createBFSDepthMatrix(matrix, Coordinate(0, 1))

The first layer is the result for output in which can be transformed into a matrix with the first directions

The other layers provide the information about a specific direction.
- Layer 1: Coming from West only
- Layer 2: Coming from North only
- Layer 3: Coming from East only
- Layer 4: Coming from South only

In [13]:
printMatrix(BFSDepthMatrix[0])

In [14]:
printMatrix(BFSDepthMatrix[1])

In [15]:
printMatrix(BFSDepthMatrix[2])

In [16]:
printMatrix(BFSDepthMatrix[3])

In [17]:
printMatrix(BFSDepthMatrix[4])

For example if we are going to remove a block (2, 10), in the initial node we can set the values from its surroundings
Below is the 3x3 dimension of the surroundings, parsing by 3, they are layers 0, 1, 2, 3, 4, respectively.

In [18]:
def set_color(value):
    color = 'white'
    if str(value).startswith('M_'):
        color = 'cyan'
    return 'background-color: %s' % color

In [19]:
test = np.concatenate((
        BFSDepthMatrix[0, 1:4, 9:12], 
        BFSDepthMatrix[1, 1:4, 9:12],
        BFSDepthMatrix[2, 1:4, 9:12],
        BFSDepthMatrix[3, 1:4, 9:12],
        BFSDepthMatrix[4, 1:4, 9:12]
    ), axis = 1).astype(str)
pd.DataFrame(test).style.applymap(set_color)

The first thing is to update the removed block cell, by getting the values from it surroundings. For example, for layer 1, which only accept values from west. Then it checks the minimum value (layer 0) from the west and set, if the from value was -1, then do nothing

In [20]:
testShow = np.copy(test)
testShow[1, 4] = 'M_(-1)'
testShow[1, 7] = 'M_(27)'
testShow[1, 10] = 'M_(-1)'
testShow[1, 13] = 'M_(13)'
pd.DataFrame(testShow).style.applymap(set_color)

Once the init cell is defined, then from this node can expand to others and will stop the sequence once from this path is much longer.
The reason of picking 4 extra layers to store the data was having already the second possibilities calculated
The idea is to reach a cell, it is only accessible from four directions. So if we store the information of 4 paths to go to a cell, if disappears one of them, it is easily get the second path to replace the disappeared one.

In [21]:
BFSDepthMatrix = createBFSDepthMatrix(matrix, Coordinate(0, 1))
modifiedMatrix = editCell(BFSDepthMatrix, Coordinate(2, 10))
print(modifiedMatrix[1:5, 2, 10])
printMatrix(modifiedMatrix[0])

[13 -1 27 -1]


In [22]:
printMatrix(modifiedMatrix[5])

In [23]:
BFSDepthMatrix = createBFSDepthMatrix(matrix, Coordinate(0, 1))
modifiedMatrix = editCell(BFSDepthMatrix, Coordinate(11, 5))
print(modifiedMatrix[1:5, 11, 5])
printMatrix(modifiedMatrix[0])

[27 -1 17 -1]


In [24]:
printMatrix(modifiedMatrix[5])

In [25]:
BFSDepthMatrix = createBFSDepthMatrix(matrix, Coordinate(0, 1))
modifiedMatrix = editCell(BFSDepthMatrix, Coordinate(8, 22))
print(modifiedMatrix[1:5, 8, 22])
printMatrix(modifiedMatrix[0])

[-1 31 -1 39]


In [26]:
printMatrix(modifiedMatrix[5])